graph LR
    subgraph LIB["PhobosLib v1.11.0"]
        INIT["PhobosLib.lua<br/>(aggregator)"]

        UTIL["Util<br/>pcallMethod, probeMethod<br/>findItemByKeywords<br/>matchesKeywords, say"]

        FLUID["Fluid<br/>tryGetFluidContainer<br/>tryAddFluid, tryDrainFluid<br/>tryGetAmount, tryGetCapacity"]

        WORLD["World<br/>scanNearbySquares<br/>findNearbyObjectByKeywords<br/>findNearbyGenerator<br/>findNearbyVehicle"]

        SANDBOX["Sandbox<br/>getSandboxVar, isModActive<br/>applyYieldMultiplier, setSandboxVar<br/>consumeSandboxFlag"]

        QUALITY["Quality<br/>getQuality, setQuality<br/>calculateOutputQuality<br/>getTier, adjustBySeverity"]

        HAZ["Hazard<br/>getRespiratoryProtection<br/>applyHazardEffect<br/>degradeFilterFromInputs<br/>isEHRActive, warnHazard"]

        SKL["Skill<br/>perkExists, getPerkLevel<br/>addXP, getXP<br/>mirrorXP, registerXPMirror"]

        RST["Reset<br/>iterateInventoryDeep<br/>stripModDataKey<br/>forgetRecipesByPrefix<br/>resetPerkXP, removeItemsByModule<br/>getWorldModDataValue<br/>stripWorldModDataKeys"]

        VAL["Validate<br/>expectItem, expectFluid<br/>expectPerk<br/>validateDependencies"]

        TRADING["Trading<br/>isDynamicTradingActive<br/>registerTradeTag<br/>registerTradeArchetype<br/>registerTradeItems<br/>registerTradeItem"]

        MIGRATE["Migrate<br/>compareVersions<br/>registerMigration<br/>registerIncompatibleHandler<br/>runMigrations<br/>notifyMigrationResult"]
    end

    subgraph CLIENT["Client-side"]
        RF["RecipeFilter<br/>registerRecipeFilter<br/>registerRecipeFilters<br/>(vanilla + Neat Crafting)"]

        TT["Tooltip<br/>registerTooltipProvider<br/>(full render replacement)"]

        LS["LazyStamp<br/>registerLazyConditionStamp<br/>(container open hook)"]

        VR["VesselReplace<br/>registerEmptyVesselReplacement<br/>(container open hook, MP sync)"]

        FS["FarmingSpray<br/>registerFarmingSpray<br/>(ISFarmingMenu hook)"]
    end

    INIT --> UTIL
    INIT --> FLUID
    INIT --> WORLD
    INIT --> SANDBOX
    INIT --> QUALITY
    INIT --> HAZ
    INIT --> SKL
    INIT --> RST
    INIT --> VAL
    INIT --> TRADING
    INIT --> MIGRATE
